### ISSUE TITLE
Using SSL

### ISSUE THREAD

**Issue by Ojaybee** [TechToSpeech/terraform-aws-serverless-static-wordpress#11]
The original [blog post](https://www.techtospeech.com/serverless-static-wordpress-on-aws-for-0-01-a-day/) states:
>By default, your WordPress installation will become available at http://wordpress.yourdomain.com (Why no SSL for this part? Check The Long Version for details)

Checking the [long version](https://www.techtospeech.com/serverless-static-wordpress-on-aws-the-long-version/)  SSL is mentioned:
>I need SSL, so I use Amazon Certificate Manager (ACM) for a free certificate which is validated by DNS records that get added to my Hosted Zone automatically by Terraform. This is all still part of this single module. Cool.

The ACM certificate exists in us-east-1 and the DNS records have been updated in Route 53 eu-west-1. My security group has port 443 open in the outbound rules (Egress from Wordpress container to world on HTTPS). 

The site cannot be accessed over https://wordpress.mydomain.com. What am I missing?

**Comment by petewilcock** [comment]
You're not missing anything - I think I've just not explained this properly in The Long Version. 

The SSL is for CloudFront point at S3, and not for the wordpress container. This is because you cannot install an ACM SSL certificate on an individual container in ECS. To make SSL work the service would either have to be behind a load balancer (too expensive) or have an SSL certificate installed into the apache configuration of the container itself - which is currently a bit too complex since we would need to use another service to install an SSL certificate on the fly. 

It's not impossible but slightly beyond the requirements of the module at the moment. One for the future, somehow :)

**Comment by CarterSheehan** [comment]
@petewilcock - Would you say that issue #17 will solve this? I'd would be great to have the added security! 😄

**Comment by petewilcock** [comment]
> @petewilcock - Would you say that issue #17 will solve this? It would be great to have the added security! 😄

Yes indeed it will do, just need to enact the appropriate mechanism to generate (and periodically refresh) the management container SSL configuration.
