### ISSUE TITLE
WordPress upgrade path?

### ISSUE THREAD

**Issue by jtatum** [TechToSpeech/terraform-aws-serverless-static-wordpress#41]
I guess EFS is used for wordpress files, allowing plugins and such to be installed in a persistent way. Is there an upgrade path for WordPress? Would you update the container, or just do it inside wordpress to update the EFS copy?

**Comment by petewilcock** [comment]
This is quite an interesting one - by default the Wordpress container won't do anything if it detects an existing Wordpress installation, so the version of the container after the first deploy _almost_ becomes redundant since it will always ask you to upgrade Wordpress as normal. 

I've upgraded several times without issue (although disk performance with EFS remains irritating for small filesystems), but always do a safety backup via UpdraftPlus first - just in case.
