### ISSUE TITLE
Permissions denied publishing to S3

### ISSUE THREAD

**Issue by nvnivs** [TechToSpeech/terraform-aws-serverless-static-wordpress#60]
Hitting on the following error during the `S3 Addon deploying` stage:

```
[Mon Apr 25 09:51:12.909555 2022] [php7:error] [pid 188] [client [IP]:16220] PHP Fatal error:  Uncaught exception 'Aws\\S3\\Exception\\S3Exception' with message 'Error executing "PutObject" on "https://s3.eu-west-3.amazonaws.com/[BUCKETNAME]/[PAGE}/index.html"; AWS HTTP error: Client error: `PUT https://s3.eu-west-3.amazonaws.com/[BUCKETNAME]/[PAGE}/index.html` resulted in a `403 Forbidden` response:\n<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>20VCEZ (truncated...)\n AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>20VCEZ4CPGENM5S3</RequestId><HostId>eBueDDL8qCDSc3GOnBtFO/qsrqKJ6784v3P/2KZh9tuR5QyRNpSoGGz+XagONO+VgoPSUtXU68U=</HostId></Error>'\n\nGuzzleHttp\\Exception\\ClientException: Client error: `PUT https://s3.eu-west-3.amazonaws.com/[BUCKETNAME]/[PAGE}/index.html` resulted in a `403 Forbidden` response:\n<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>Ac in /var/www/html/wp-content/plugins/wp2static-addon-s3/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195, referer: http://[SITENAME]/wp-admin/admin.php?page=wp2static
```

Looks like it's the same issue reported here: https://github.com/WP2Static/wp2static/issues/797. Confirmed that can workaround change the `Object ACL` under the `S3 Publishing Options` to `private`. Did i miss something on my setup, or is this a required setting that could be defaulted?

Also this https://github.com/WP2Static/wp2static/issues/537 talks about similar issue and the IAM role permissions are different. Going to have a try with those

**Comment by petewilcock** [comment]
The bucket for the module is already private and enforced by public access block settings. There is a bucket policy that allows access to `GetObject` via the CloudFront Origin Access Identity (OAI) that is set up by default. So CloudFront can access the bucket contents publicly, and nothing else can. 

For the publish step on the WP2Static plugin, you have two authentication options - explicit AWS User keys (bad), or the default credential chain which uses the role assigned to the ECS container. That role has S3:PutObject permissions to the target S3 bucket used by CloudFront. 

This sounds like a duplicate of https://github.com/TechToSpeech/terraform-aws-serverless-static-wordpress/issues/15 where I've noted the WP2Static plugin is not 100% pre-configured by default, as the S3 module needs activation and the ACL should be set to private which it's not. 

Essentially you can't have public objects in a private bucket (the 'Block all public access' prevents this), so that's almost certainly the source of the error.

**Comment by nvnivs** [comment]
ah! i thought i saw this mentioned somewhere and could not find the issue.... Sorry about that!

I'll close this one, wanted to make sure there was an issue covering and the existing one cover both this issue and enabling the module.
